### ISSUE TITLE
InnerBlocks / JSX support

### ISSUE THREAD

**Issue by ju5t** [beaverbuilder/bb-example-acf-blocks#1]
Let me start with thanking you for making ACF blocks possible in BB. It's amazing.

We have a requirement to support `<InnerBlocks />` in our app. Unfortunately, for this to work, you need JSX support in the block, because otherwise it wouldn't know how to parse this.

Are there any plans to add JSX support or do you perhaps have an alternative solution for it?

**Comment by fastlinemedia** [comment]
@ju5t thanks for the message. Unfortunately, to get inner blocks working in BB, we'd have to load the entire block editor somehow. Even if we had JSX support in modules, that wouldn't help. 

We are working on our own form of inner blocks (called container modules right now). Once that's done, we _might_ be able to support inner blocks built with ACF, but that's still a way out. 

Sorry I don't have a better answer! 

Justin

**Comment by ju5t** [comment]
No worries! It's pretty awesome already that we can build blocks with ACF.
